# Generated by Django 3.1.3 on 2021-01-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='rent_pics'),
        ),
    ]
