# Generated by Django 3.1.3 on 2021-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='accessries',
        ),
        migrations.AddField(
            model_name='rent',
            name='accessory_1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='accessory_2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='accessory_3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='accessory_4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='accessory_5',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='present_Value',
            field=models.FloatField(default=2500),
        ),
    ]
